controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_v1:
    resource:
        path: ../src/API/Common/V1/
        namespace: App\API\Common\V1
    type: attribute
    prefix: '/api/v1'